### ISSUE TITLE
CurseForgeにアップしませんか？

### ISSUE THREAD

**Issue by KameiB** [Yukkuritaku/unicode-fix#1]
Modrinth でこの素敵なモッドを発見したのですが、僕がプレイするモッドパックはほとんどCurseForge にアップされています。
よかったらUnicode FixをCurseForge にもアップしてもらえませんか？

よろしくお願いします。

**Comment by Yukkuritaku** [comment]
コメントありがとうございます。
つい先ほど[CurseForge](https://www.curseforge.com/minecraft/mc-mods/unicode-fix)にアップロードしました！(多分)承諾も完了しているのでModpackに使えると思います。
Modpackにも自由に使っていいですよ！

**Comment by KameiB** [comment]
お早い対応ありがとうございました！
では、クローズさせていただきます。
