### ISSUE TITLE
Does not fix splashtext unicode issues.

### ISSUE THREAD

**Issue by reallydrained** [Yukkuritaku/unicode-fix#2]
I am on Windows 11 and I am putting together a modpack. I have custom splashtexts with colored text and special characters, including Japanese/Chinese/Korean. Apparently it always appears broken (on 1.7.10 at least) for Windows, so I found a fix which is a JVM argument: `-Dfile.encoding=UTF-8` this is the only way I've been able to fix the issue. I have been looking for a solution like your mod to fix this issue since I can't put a JVM argument in a modpack .zip but I can obviously put mods so I tried yours but sadly all the special characters appear broken like before without the Java argument. The § symbol used for color coding even shows up as the "Ā" symbol. I have attached screenshots below. I could provide symbols from the special splashtexts if that would help, anything I can do just let me know.

![Screenshot 2024-12-02 214827](https://github.com/user-attachments/assets/5df04897-589a-4197-964c-172a950b4c07)
![Screenshot 2024-12-02 214858](https://github.com/user-attachments/assets/e183503f-34f7-43d7-bca5-18ec29361cc4)
![Screenshot 2024-12-02 215000](https://github.com/user-attachments/assets/5049ef79-b576-4cab-8955-d3f02600472c)
![Screenshot 2024-12-02 214051](https://github.com/user-attachments/assets/58ce3564-b842-40fc-80d8-13c63a2810aa)

**Comment by Yukkuritaku** [comment]
It looks like wrong text encoding...?
From I tested in my custom resource pack(`splashes.txt` with UTF-8), i dont see the issue.
Can you provide the your `splashes.txt?`

もしかしたらテキストエンコードが間違ってるかも...?
自分のリソースパック(UTF-8の`splashes.txt`)で試しても問題が見つからんかったです...
もしよろしければ`splashes.txt`を送ってもらってもよろしいですか？
![スクリーンショット (2148)](https://github.com/user-attachments/assets/85fa17e6-c4a7-4df7-9ac6-c3bc3b5a7d61)
![スクリーンショット (2149)](https://github.com/user-attachments/assets/62fb747d-5421-4b01-87c7-2caac691e454)
![スクリーンショット (2150)](https://github.com/user-attachments/assets/ac6e6734-47da-44b8-b61e-abcdd66a3b67)

**Comment by reallydrained** [comment]
There are a lot of splashtexts I made so I picked out ones that are definitely broken:
私が作成したスプラッシュテキストはたくさんあるので、明らかに壊れているものを選択しました:
```
我喜欢我的世界!
§aLovely!
다문화는 정말 놀랍습니다!
§fⒸ 2024 TPM. All Rights Reserved.
Водка
§61337 h4x0r mode activated!
最高に楽しい時間！
§4§lMighty Dragon Love Infinity ☭
Ichiban Playground™
Minecraft Love ClubⓇ
Delete §6C:\Windows\System32 §rfolder to improve FPS!
```
This is exactly how they are typed, copied from the splashes.txt file. Am I maybe supposed to be typing them like this: `\u00A7a`? Maybe this is my issue, I am not sure though. If you think it would fix it I could retype them all but then I am not sure what to do about the Japanese/Chinese/Korean/Russian splashtexts. Doing the `\u00A7a` versions only would work for special characters like these: `Ⓡ ™ § Ⓒ ☭`

これは、テキスト ファイルからコピーされた、まさに入力された方法です。次のように入力する必要があるのでしょうか: `\u00A7a`? たぶんこれが私の問題なのでしょうが、よく分かりません。全部入力し直せば解決すると思うのですが、他の言語についてはどうすればいいのかわかりません。`\u00A7a` バージョンのみを実行すると、次のような特殊文字に対して機能します: `Ⓡ ™ § Ⓒ ☭`
<br/>
Sorry if the translation is really bad, I just used google translate to maybe help but I am not sure if it's bad. Thank you for trying to help me!
翻訳が下手だったらごめんなさい。Google 翻訳を使ってみましたが、下手かどうかはわかりません。助けてくださってありがとうございます!

**Comment by Yukkuritaku** [comment]
そのテキストをコピーして試してみたのですが、UTF-8に変換されている`splashes.txt`だと大丈夫に見えます
↓自分が試したやつ
[splashes.txt](https://github.com/user-attachments/files/18001921/splashes.txt)
自分は[notepad++](https://notepad-plus-plus.org/)でテキストを編集しているのですが、そっちで編集すると直る可能性があるかもしれません (テキストのバックアップは忘れないようにしてください！)
![スクリーンショット (2161)](https://github.com/user-attachments/assets/7281fd71-a330-4ba8-8aa6-8df6b20d8df0)
![スクリーンショット (2158)](https://github.com/user-attachments/assets/0099715a-366a-461d-9d6c-6e4cd28af2de)
![スクリーンショット (2156)](https://github.com/user-attachments/assets/fe5bda0c-9fa7-4bca-9241-e9634c2f3f98)

**Comment by reallydrained** [comment]
> そのテキストをコピーして試してみたのですが、UTF-8に変換されている`splashes.txt`だと大丈夫に見えます ↓自分が試したやつ [splashes.txt](https://github.com/user-attachments/files/18001921/splashes.txt) 自分は[notepad++](https://notepad-plus-plus.org/)でテキストを編集しているのですが、そっちで編集すると直る可能性があるかもしれません (テキストのバックアップは忘れないようにしてください！)

I tried the file you sent and it is still the exact same issues =/
送っていただいたファイルを試してみましたが、やはり同じ問題が起こります =/

**I tried it with Force Unicode ON:**
ユニコードを強制オン:
![Screenshot (9)](https://github.com/user-attachments/assets/31eed926-4f8d-4bd1-862f-551d23e4a0eb)
![Screenshot (10)](https://github.com/user-attachments/assets/8dc81458-430b-4ffd-94ec-f6d9abb31743)
![Screenshot (11)](https://github.com/user-attachments/assets/f8d63339-17f9-45e1-bffd-85e8183dfe0a)

**Then I also tried with Force Unicode OFF:**
ユニコードを強制オフ:
![Screenshot (12)](https://github.com/user-attachments/assets/ebffcb4e-c0cd-45f7-b691-7a9f3536a0ab)
![Screenshot (13)](https://github.com/user-attachments/assets/acea083d-8c0f-49de-a69a-36357c335845)

I made a brand new game instance with only the mod for custom main menu/splashtext and the Unicode Fix mod. There must be a difference with your game and mine though, I was thinking maybe because I play in English but I don't know how that would change anything 🤷‍♂️ I also forgot to mention I use Notepad++ as well! It does not seem to make a difference though sadly.
カスタム メイン メニュー/スプラッシュ テキストの mod と Unicode Fix mod のみを使用して、まったく新しいゲーム インスタンスを作成しました。でも、あなたのゲームと私のゲームには違いがあるはずです。英語でプレイしているからかもしれないと思っていましたが、それがどう変わるのかはわかりません。🤷‍♂️ また、Notepad++ も使用していることを忘れていました。残念ながら、違いはないようです。
<br/>
**Sorry, I did not mean to close and reopen the issue!**
申し訳ありませんが、問題を閉じて再開するつもりはありませんでした。
<br/>
**EDIT:** I tried the other versions like: `\u00A76 \u00A74 \u24B8 \u00A7f \u24C7 \u00A7a` but those did not work either and I tried it with force Unicode on and off. I am confused because it seems like the only way I can get them to show up right is with the JVM (Java) argument `-Dfile.encoding=UTF-8` but I am using Windows and so are you so I don't get why only the argument works for me and not the mod.
次のような他のバージョンも試しました: `\u00A76 \u00A74 \u24B8 \u00A7f \u24C7 \u00A7a` しかし、これらも機能しなかったため、Unicode の強制をオン/オフにしてみました。それでも機能しません。正しく表示させる唯一の方法はJVM（Java）引数を使うことのようだと混乱しています `-Dfile.encoding=UTF-8` しかし、私は Windows を使っており、あなたも Windows を使っているので、なぜこの議論だけが私には有効で、mod には有効でないのか理解できません。

**Comment by Yukkuritaku** [comment]
この現象を見るのは初めてですね...🥴
こうなってくるとMinecraftの問題ではなくWindowsやMinecraft Launcherの可能性も出てくるかもしれません...
Minecraft Launcherはどのソフトを使ってますか？

**Comment by reallydrained** [comment]
> この現象を見るのは初めてですね...🥴
> こうなってくるとMinecraftの問題ではなくWindowsやMinecraft Launcherの可能性も出てくるかもしれません...
> Minecraft Launcherはどのソフトを使ってますか？

I use Prism Launcher, I have been testing this on both windows 10 and windows 11 =/ I just know that for windows the Unicode characters appear broken unless you use the JVM (Java) argument `-Dfile.encoding=UTF-8`. That is what I read online anyways. My solution to this was to use your mod (because I cannot include JVM argument with my modpack .zip, it is a launcher option) so I really want to get this working. I feel like there has to be a way to make it work because the JVM argument *does* fix it.

私は Prism Launcher を使用しています。Windows 10 と Windows 11 の両方でこれをテストしています =/ Windows では、JVM (Java) 引数 `-Dfile.encoding=UTF-8` を使用しない限り、Unicode 文字が壊れて表示されることがわかっています。とにかく、それは私がオンラインで読んだことです。これに対する私の解決策は、あなたの mod を使用することです (modpack .zip に JVM 引数を含めることができないため)。これが機能することを願っています。これは JVM 引数によって修正されるため、これを機能させる方法があるはずです。

**Comment by Yukkuritaku** [comment]
Prism Launcherで試してみましたが、残念ながらそのような現象は自分には起こりませんでした...
Jreはどの物を使用してますか？
後はVanillaのMinecraft Launcherでも同じ現象が起こるのかが気になります

それと起動するとログに現在の`file.encoding`を表示するものを組み込んだjarを用意したので、それで起動してみてログを送信してもらいたいです
自分の環境だとPrism Launcher、VanillaのMinecraft Launcherでも`MS932`で表示されます、開発環境(Intellij Idea)であれば`UTF-8`と表示されます
[1.7.10-unicodefix-1.3.zip](https://github.com/user-attachments/files/18022732/1.7.10-unicodefix-1.3.zip)
[diffはこんな感じです](https://github.com/Yukkuritaku/unicode-fix/commit/6f3750c0b25e09257abd86e16062c5f4fe7b72c9)

(ちなみに調べた感じ、Javaのコード内だと`file.encoding`を設定できないっぽいんですよね...何か他にいい方法があればいいのですが今の所見つからず...)

**Comment by reallydrained** [comment]
> Jreはどの物を使用してますか？

I am using the latest possible Java 8 which is 8u432 by Temurin (https://adoptium.net/temurin/releases/?version=8)
I had the same issue using the default JRE 8 Minecraft comes with for 1.7.10 which is 8u51 but at some point recently I upgraded to the newest one.
私は、Temurin による最新の Java 8、8u432 を使用しています (https://adoptium.net/temurin/releases/?version=8)
Minecraft に付属する 1.7.10 のデフォルトの JRE 8、8u51 を使用しても同じ問題が発生しましたが、最近になって最新のものにアップグレードしました。

I will load that .jar you sent and send you the whole log, sorry I have been a little busy the past couple days I did not get a chance to reply. I am so confused why this won't work for me except with the JVM argument. I will update this comment as soon as possible with the log running the version you sent.
送信していただいた .jar をロードして、ログ全体を送信します。申し訳ありませんが、ここ数日は少し忙しく、返信する時間がありませんでした。JVM 引数以外では、なぜこれが機能しないのか、とても困惑しています。送信していただいたバージョンを実行しているログをできるだけ早くこのコメントに更新します。
<br/>
Okay, I ran the .jar you sent with the `-Dfile.encoding=UTF-8` JVM argument OFF so it doesn't interfere and splashtexts are broken. Here is the log: https://gist.githubusercontent.com/reallydrained/96219b838726f49e1d2e7ecf89dd8f65/raw/46d137e5b17836cf5b6a4167495ca5cc1621b7f9/fml-client-latest.log
わかりました。送信された .jar を `-Dfile.encoding=UTF-8` JVM 引数をオフにして実行したので、干渉は発生せず、スプラッシュ テキストは依然として壊れています。ログは次のとおりです: https://gist.githubusercontent.com/reallydrained/96219b838726f49e1d2e7ecf89dd8f65/raw/46d137e5b17836cf5b6a4167495ca5cc1621b7f9/fml-client-latest.log
<br/>
I ran the .jar on my very bad laptop because I am not home right now but it should not make a difference, the issue has been the exact same on both my PC and this crappy laptop. It does not seem to make a difference between windows 10/11 or good/bad computers.
私は今家にいないので、非常に調子の悪いラップトップで .jar を実行しましたが、違いはないはずです。問題は私の PC とこのひどいラップトップの両方でまったく同じです。Windows 10/11 や、良い/悪いコンピューターの違いはないようです。

**Comment by Yukkuritaku** [comment]
ログを確認してmod環境を再現した結果、[GTNHのCustom Main Menu](https://github.com/GTNewHorizons/Custom-Main-Menu)が原因ってことがわかりました！
問題は`splashes.txt`を読み込む際、`InputStreamReader`にUTF-8を指定していないのが原因みたいです。
[ここのコードですね](https://github.com/GTNewHorizons/Custom-Main-Menu/blob/master/src/main/java/lumien/custommainmenu/lib/texts/TextResourceLocation.java#L35)
![スクリーンショット (2162)](https://github.com/user-attachments/assets/7a8b7545-184d-4c9e-ad2a-0c3a7db7dea2)
幸い、このバグはasmで置き換えることが可能なのでこちらで修正が可能です！
(まだ数ヶ月前にコードが更新されてるっぽいのでプルリクエストを送れば直してくれるのでしょうが...)

まあそこら辺はまた今度考えるとして、今はこちらの方でasmを使って置き換える形で修正しました！
後でGithub、CurseForge、Modrinthで更新しておきます
![スクリーンショット (2164)](https://github.com/user-attachments/assets/d4789351-71f4-49e2-96b2-52d1a83dfa6a)

公開しておきました！(https://modrinth.com/mod/unicode-fix/version/1.3.1-1.7.10)

**Comment by reallydrained** [comment]
Thank you so much!!! IT WORKS! I am so excited =D for the first time ever the splashtexts work without the JVM argument on =) I did not think this issue would be resolved easily so I am very happy it works. It would definitely be a great idea to report this issue to GTNH Custom Main Menu people so it can be fixed, what you did definitely works! I am so excited I will not have to add a note telling Windows users to use the JVM argument to fix broken text. Now my modpack can have special characters work fine =D Thank you for figuring this out!
本当にありがとうございます!!! うまくいきました! とても興奮しています =D JVM 引数なしでスプラッシュ テキストが機能したのは今回が初めてです =) この問題がこんなに簡単に解決されるとは思っていなかったので、うまくいってとても嬉しいです。GTNH Custom Main Menu の担当者に報告して修正してもらうのが間違いなく良い考えだと思います。あなたのやり方は間違いなくうまくいきました! Windows ユーザーに壊れたテキストを修正するために JVM 引数を使用するように指示するメモを追加する必要がなくなるので、とても興奮しています。これで、特殊文字が modpack でうまく機能します =D この問題を解決していただき、ありがとうございます!
___
**EDIT:** I seem to have found a new issue. xD Now that I have the splashtexts working with the new mod version there is an issue with my colored text for custom items. I added these items using the Custom Items mod 1.0.8:
(https://github.com/marcel0ll/CustomItems)
(https://www.curseforge.com/minecraft/mc-mods/customitems/files/2223670)
**編集:** 新しい問題が見つかったようです。xD 新しい mod バージョンでスプラッシュテキストが機能するようになったので、カスタム アイテムの色付きテキストに問題があります。カスタム アイテム mod 1.0.8 を使用して次のアイテムを追加しました:
(https://github.com/marcel0ll/CustomItems)
(https://www.curseforge.com/minecraft/mc-mods/customitems/files/2223670)

![2024-12-07_19 47 02](https://github.com/user-attachments/assets/958c6a4d-9e1f-403d-a1d1-37bc55d47b99)
*I added some inappropriate items during testing so I covered those up xD -- the green "Ā" symbol on the left side zoomed in block is expected because that text is supposed to be green but it is not supposed to show "Ā" in place of the "§" symbol, this is the same issue as before with splashtexts.
テスト中に不適切なアイテムを追加したので、それらを隠しました xD -- 左側の拡大されたブロックに緑色の「Ā」記号が表示されるのは、そのテキストが緑色になるはずであるため予想されますが、「§」記号の代わりに「Ā」が表示されるはずはなく、これはスプラッシュテキストの以前の問題と同じです。*

I add items using .json files like this:
次のように .json ファイルを使用してアイテムを追加します:
```{
    "blocks":
    [
        {
            "name": "§dMissing Texture§r",
            "creativeTab": "Test Custom Items",
            "textureName": "missing_texture",
            "material": "rock",
            "stepSound": "metal",
            "hardness": 0,
            "resistance": 0,
            "registerOrder": 5
        }
    ]
}
```
___
![2024-12-07_19 47 21](https://github.com/user-attachments/assets/80416ddc-08d3-48cf-9b1a-f661e1645f36)
Weirdly, custom tooltip text shows up properly. These are added using zenscript text files with the mod CraftTweaker 3.1.0
(https://github.com/CraftTweaker/CraftTweaker)
(https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/2838720)
奇妙なことに、カスタム ツールチップ テキストが正しく表示されます。これらは、zenscript テキスト ファイルを使用する mod CraftTweaker 3.1.0 を使用して追加されます。
(https://github.com/CraftTweaker/CraftTweaker)
(https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/2838720)

I add custom tooltips using .zs text files like this:
次のように .zs テキスト ファイルを使用してカスタム ツールチップを追加します:
```<backpacks16840:backpack:*>.addTooltip(format.green("Shift + Right Click to open backpack from inventory."));```

Documentation for this can be found here:
https://docs.blamejared.com/MineTweaker/en/tutorials/1.7.x/tooltips
これに関するドキュメントはここにあります:
https://docs.blamejared.com/MineTweaker/en/tutorials/1.7.x/tooltips

**Comment by Yukkuritaku** [comment]
このCustom Itemsの件、もしかしたらunicode fixで修正するよりもフォークして修正する方が良いかもしれません
理由としてはjsonの読み込み自体がテキストエンコード事態に干渉していて、しかも`name`が変わるとアイテムidも変わるようになっているので、こちらのmodで直してしまうと予期せぬアイテム消滅を招く可能性があるんですよね...
直すのには少し時間がかかってしまうと思います、気長に待っていただけると嬉しいです

**Comment by reallydrained** [comment]
Oh man damn, I see! I did not think the mod itself was broken like that 0.0 I will maybe just remove colored names for the time being until there is some solution. I was trying to think of a fix and the one thing I could think of was editing the `en_US.lang ` file to change block names but this mod does not even use that method as you said (to my understanding anyways). By the way, I think this issue of block IDs changing might already be happening sadly because since I have had the new version of Unicode Fix (1.3.1) when I start my worlds it seems to always tell me that there are missing blocks (my custom items) but it didn't do this before unless I had added items or changed something. I did not realize why this was happening but now that you said it I think you're right.
ああ、なるほど！ mod 自体がそのように壊れているとは思っていませんでした 0.0 解決策が見つかるまでは、当面は色付きの名前を削除するだけにします。修正方法を考えようとしていて、思いついたのは `en_US.lang ` ファイルを編集してブロック名を変更することだけでしたが、この mod ではあなたが言ったようにその方法さえ使用されていません (少なくとも私の理解では)。ところで、ブロック ID が変更されるこの問題は悲しいことにすでに発生しているのではないかと思います。Unicode Fix の新しいバージョン (1.3.1) をインストールしてからは、ワールドを開始するときに、ブロック (カスタム アイテム) が不足していると常に表示されるようですが、アイテムを追加したり何かを変更したりしない限り、以前はこのようなことは起こりませんでした。なぜこのようなことが起こるのかわかりませんでしたが、あなたが言ったので、あなたが正しいと思います。
![Capture](https://github.com/user-attachments/assets/3fbe769b-6522-47d6-b957-a1803ed8cf49)

**Comment by Yukkuritaku** [comment]
時間かかってしまってすいません、Custom Itemsをフォークして修正したバージョンを公開したのでそちらをチェックしていただけると嬉しいです！
jsonの読み込みがUTF-8にならないのと、アイテムidに色つきの名前がつかないようにしています(これをしておかないと、giveコマンドで入手が不可になってしまう)
アイテム名はちゃんと色つき文字になっています
(https://github.com/Yukkuritaku/CustomItems/releases/tag/1.0.10-fork-fix)

**Comment by Yukkuritaku** [comment]
ただ、色つきの指定をしていたアイテムidは一度消滅してしまうと思うので気を付けてください

**Comment by reallydrained** [comment]
Hey, this is awesome! Thank you for trying to fix these issues. I have done some testing with the forked version you made and there seems to be an issue, the colored names appear totally normal which is great but now none of my custom items show up. Only the blocks I have added appear, the items and tools are all nowhere to be found even though I am using the same textures and .json files from before. The custom creative tab works, all of the blocks work, but I cannot get my items or tools to show up in the game now and I am not sure why. They all worked before with version 1.0.9 so I am not sure what the issue is but maybe you know what has changed if anything?
すごいですね！これらの問題を修正しようとしていただきありがとうございます。あなたが作成したフォーク バージョンでいくつかテストしてみましたが、問題があるようです。色付きの名前はまったく正常に表示され、これは素晴らしいのですが、カスタム アイテムがまったく表示されなくなりました。追加したブロックのみが表示され、以前と同じテクスチャと .json ファイルを使用しているにもかかわらず、アイテムとツールはすべてどこにも見つかりません。カスタム クリエイティブ タブは機能し、すべてのブロックは機能しますが、アイテムやツールがゲームに表示されなくなり、その理由がわかりません。バージョン 1.0.9 では以前はすべて機能していたので、何が問題なのかわかりませんが、何が起こっているのかおわかりになるでしょうか。
***
By the way, I am not totally sure what you mean by 'item IDs that you have specified as colors will disappear at some point" but if you mean the items will disappear from old saves I do understand that and it is no issue! If you mean to say items/blocks with colored names are generally unstable then I'd be curious to know more. I never set the item's ID with color codes, only the actual item title. Here is an example:
また、「色として指定したアイテム ID は、ある時点で消える」とはどういう意味かわかりませんが、古いセーブからのアイテムが消えるという意味であれば、それは理にかなっていて問題ありません。色付きの名前付きアイテム/ブロックが一般的に不安定であるという意味であれば、詳細を知りたいです。私はアイテム ID を色コードで設定することはなく、実際のアイテム タイトルのみを設定します。次に例を示します:
```json
{
    "blocks":
    [
        {
            "name": "§aGreen Screen§r",
            "creativeTab": "Custom Tests",
            "textureName": "green_screen",
            "material": "clay",
            "stepSound": "cloth",
            "hardness": 0,
            "resistance": 1200,
            "registerOrder": 6
        }
    ]
}
```
***
I thought it would also maybe be good to tell you that none of my items or tools have colored names, so it isn't anything like that causing issues I don't think. Here is an example of one of my items that worked before but now does not appear at all:
また、私のアイテムやツールには色付きの名前を付けていないので、それが問題の原因ではないと思います。以下は、以前は機能していたが、現在はまったく表示されないアイテムの例です:
```json
{
    "items": [
        {
            "name": "Elytra Left Wing",
            "textureName": "elytra_left_wing",
            "creativeTab": "Custom Tests",
            "maxStackSize": 1,
            "registerOrder": 11
        }
    ]

}
```
***
**EDIT: I just realized something, I have been using version 1.0.9 (beta) because I had some weird issues with version 1.0.10 (alpha) and I don't remember what the issues were exactly but one thing was that I could not get items in the game properly for some reason. I think version 1.0.10 did not work as well at all and that is why I use 1.0.9, I think that is what the issue is here. I don't think you messed anything up, there is just some difference between 1.0.9 and 1.0.10 that makes it broken and seemingly unstable compared to the beta.
I looked and there are source files for 1.0.9 available here: https://github.com/marcel0ll/CustomItems/releases/tag/1.0.9b
I also found a changelog for 1.0.10 here: https://www.curseforge.com/minecraft/mc-mods/customitems/files/2311475**
**編集: 今気づいたのですが、バージョン 1.0.10 (アルファ) で奇妙な問題が発生したため、バージョン 1.0.9 (ベータ) を使用していました。問題が何だったのか正確には覚えていませんが、何らかの理由でゲーム内でアイテムを適切に取得できなかったことが 1 つありました。バージョン 1.0.10 がまったくうまく動作しなかったため、バージョン 1.0.9 を使用しています。編集によって mod が壊れるのではなく、これが問題だと思います。1.0.9 と 1.0.10 にはいくつかの違いがあり、ベータ バージョンと比較して壊れて不安定になっています。
調べてみたところ、1.0.9 のソース ファイルはここにあります: https://github.com/marcel0ll/CustomItems/releases/tag/1.0.9b
また、1.0.10 の変更ログはここにあります: https://www.curseforge.com/minecraft/mc-mods/customitems/files/2311475**

**I think if you were to apply all the edits you made to 1.0.10 to version 1.0.9 instead everything would work as intended. I am betting this is the issue.
1.0.10 に対して行われたすべての編集をバージョン 1.0.9 に適用すれば、問題は修正されると思います。これが問題の原因であることはほぼ間違いありません。**

**Comment by Yukkuritaku** [comment]
1.0.10の問題を模索したところ、Ex Nihiroとの互換性を実装しているコードに問題があって、そこでエラーが発生するとアイテム登録が止まってしまうようです。
その互換性コードを無効にしたところ、ちゃんとアイテムが登録されたのでその修正をしたバージョンをリリースしようと思います

> By the way, I am not totally sure what you mean by 'item IDs that you have specified as colors will disappear at some point" but if you mean the items will disappear from old saves I do understand that and it is no issue! If you mean to say items/blocks with colored names are generally unstable then I'd be curious to know more. I never set the item's ID with color codes, only the actual item title.

これは不安定になるってことじゃなくて古いセーブから一度消えちゃうってことです！文章の書き方が曖昧ですいません
例えばアイテム名が`§aGreen Screen§r`だった場合、フォーク前のmodはアイテムidの指定が`§agreen_screen§r`になるようになっているのですが、自分がフォークした方だとカラーコードが外され、アイテムidが`green_screen`になるので`§agreen_screen§r`のアイテムは消えちゃうんですよね
一度フォークした方でワールドに入れば新しい方のアイテムは消えることはなくなると思います！(多分)

**Comment by reallydrained** [comment]
> 1.0.10の問題を模索したところ、Ex Nihiroとの互換性を実装しているコードに問題があって、そこでエラーが発生するとアイテム登録が止まってしまうようです。 その互換性コードを無効にしたところ、ちゃんとアイテムが登録されたのでその修正をしたバージョンをリリースしようと思います

Okay! Awesome, thank you so much for fixing this stuff. I wasn't sure what was wrong with version 1.0.10 but I am happy you figured it out because I am sure it's best to use the newest one if possible. I am excited to use the new fixed version =D
わかりました！素晴らしいです。この問題を修正していただき、本当にありがとうございます。バージョン 1.0.10 の何が問題だったのかわかりませんでしたが、可能であれば最新のバージョンを使用するのがベストだと確信しているので、解決できたことを嬉しく思います。修正された新しいバージョンを使用するのが楽しみです =D

> これは不安定になるってことじゃなくて古いセーブから一度消えちゃうってことです！文章の書き方が曖昧ですいません 例えばアイテム名が`§aGreen Screen§r`だった場合、フォーク前のmodはアイテムidの指定が`§agreen_screen§r`になるようになっているのですが、自分がフォークした方だとカラーコードが外され、アイテムidが`green_screen`になるので`§agreen_screen§r`のアイテムは消えちゃうんですよね 一度フォークした方でワールドに入れば新しい方のアイテムは消えることはなくなると思います！(多分)

Ahhh yes I understand! I wasn't sure what you meant but now I get it. I was aware this could happen and it shouldn't be an issue, I haven't used any of the custom items in my survival worlds. So far I have only used them in test worlds. I really appreciate you fixing these issues and explaining it all to me =) Thank you!!
ああ、はい、分かりました！何を意味しているのか分かりませんでしたが、今は理解できました。このようなことが起こる可能性があることは知っていましたし、問題になるはずもありません。私はサバイバル ワールドでカスタム アイテムを一切使用していません。今のところ、テスト ワールドでのみ使用しています。これらの問題を修正して、すべて説明していただき、本当に感謝しています =) ありがとうございます!!

**Comment by Yukkuritaku** [comment]
リリースしました！
Ex Nihiroのハンマー互換性を削除してるのでこれで登録されるはずです
https://github.com/Yukkuritaku/CustomItems/releases/tag/1.0.11-fork-fix

**Comment by reallydrained** [comment]
> リリースしました！ Ex Nihiroのハンマー互換性を削除してるのでこれで登録されるはずです https://github.com/Yukkuritaku/CustomItems/releases/tag/1.0.11-fork-fix

Everything seems to work fine now =D thank you so much! This is very exciting, I don't think there are any issues with text now at all and before there were so many. I really appreciate you doing all of this.
今はすべて正常に動作しているようです =D 本当にありがとうございます! これはとてもうれしいです。以前はたくさんあったテキストの問題が今ではまったくないと思います。これらすべてを行っていただき、本当に感謝しています。
